# Generated by Django 5.2.6 on 2025-09-24 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.industry'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='api_applica_applica_2c7a92_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='api_applica_job_id_51a272_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='api_applica_job_id_cbf0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'created_at'], name='api_applica_job_id_02c277_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='api_applica_applica_bb21b9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'created_at'], name='api_applica_applica_8c66e1_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['industry'], name='api_job_industr_d46b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location_type'], name='api_job_locatio_2f52b5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['type'], name='api_job_type_947608_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_min', 'salary_max'], name='api_job_salary__943a04_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='api_job_created_f81cf5_idx'),
        ),
    ]
